"""Shared detail card widgets."""

from desktop.shared.detail.card import (
    ADD_TITLE_PREVIEW_CARD_PROFILE,
    CANDIDATE_DETAIL_CARD_PROFILE,
    DETAIL_CARD_LAYOUT_PROFILE,
    DetailCardLayoutProfile,
    LIST_ITEM_HEIGHT,
    LIST_ITEM_H_PADDING,
    LIST_ITEM_V_PADDING,
    LIST_TEXT_GAP,
    LIST_THUMB_HEIGHT,
    LIST_THUMB_WIDTH,
    POSTER_BASE_HEIGHT,
    POSTER_BASE_WIDTH,
    POSTER_DISPLAY_SCALE,
    POSTER_HEIGHT,
    POSTER_WIDTH,
    RatingCircleIndicator,
    WatchedDetailCard,
    WatchedListItemDelegate,
    _elide_text,
    _load_list_thumb_pixmap,
    fit_poster_pixmap_for_display,
)

__all__ = [
    "ADD_TITLE_PREVIEW_CARD_PROFILE",
    "CANDIDATE_DETAIL_CARD_PROFILE",
    "DETAIL_CARD_LAYOUT_PROFILE",
    "DetailCardLayoutProfile",
    "LIST_ITEM_HEIGHT",
    "LIST_ITEM_H_PADDING",
    "LIST_ITEM_V_PADDING",
    "LIST_TEXT_GAP",
    "LIST_THUMB_HEIGHT",
    "LIST_THUMB_WIDTH",
    "POSTER_BASE_HEIGHT",
    "POSTER_BASE_WIDTH",
    "POSTER_DISPLAY_SCALE",
    "POSTER_HEIGHT",
    "POSTER_WIDTH",
    "RatingCircleIndicator",
    "WatchedDetailCard",
    "WatchedListItemDelegate",
    "_elide_text",
    "_load_list_thumb_pixmap",
    "fit_poster_pixmap_for_display",
]
